/** @file ScQtSimulator.h
 *  @brief A semi general purpose simulator for SystemC task, using Qt's stuff
 *  Ideas taken from  http://fabienpn.wordpress.com/qt-thread-multiple-methods-with-sources/
 *  https://www.researchgate.net/publication/228972213_gSysC_A_graphical_front_end_for_SystemC
 *  and https://github.com/mortbopet/Ripes
 */
/*
 *  @author János Végh (jvegh)
 *  @bug No known bugs.
 *
 *  Last edited 2026.04.14
*/

#ifndef SCQTSIMULATOR_H
#define SCQTSIMULATOR_H

//#include <sysc>
#include "sysc/kernel/sc_simcontext.h"
#include "sysc/kernel/sc_time.h"
#include <QObject>
#include <QMutex>
#include <QTime>
#include <QWaitCondition>

using namespace std;

// Benchmarking is abused here; to not repeat the code, is used unconditionally
#define MAKE_TIME_BENCHMARKING  // Do not remove; used to measure processor time
#ifdef MAKE_TIME_BENCHMARKING
#include "MacroTimeBenchmarking.h"    // Must be after the '#define MAKE_TIME_BENCHMARKING' to have its effect
#endif

/*!
 * \class ScQtSimulator
 * \brief  Implements a semi-general SystemC simulator, based on Qt technology
 *
 * The idea is that the simulator repeatedly starts the SystemC engine
 * (internally stopping at SystemC events, generated by the tested system).
 * It is assumed that the system-under-test unit uses "heartbeating",
 * that is, the system steps from one simulated time to the other,
 * an the time adapts to the actual situation.
 * The simulator can be triggered to use different methods of execution,
 * including one for stopping after a given number of events (typically, heartbeats)
 * or after a given period of simulated time.
 * It benchmarks three types of execution times: the simulated (biological) time,
 * the simulated time (the processor time to process the algorithms)
 * and the user time (the typically interactive user needs to browse the simulation).
 * The times can be reset.
 */

class ScQtSimulator : public QObject
{
    Q_OBJECT

public:
    explicit ScQtSimulator(QObject *parent = 0);
    /**
     * @brief This enum describes the various available methods
     */
    enum Method {
        Method_SingleSteps = 1,
        Method_SimulatedTime = 2,
        Method3 = 3
    };
    /**
     * @brief Requests for the method @em method to be executed
     *
     * This method defines #_method and set #_abort to interrupt current method.
     * It is thread safe as it uses #mutex to protect access to #_method and #_abort variable.
     */
    void requestMethod(Method method);
    /**
     * @brief Requests the process to abort (an emergency stop)
     *
     * It is thread safe as it uses #mutex to protect access to #_abort variable.
     */
    void abort();
    // Return user time of simulation, in seconds
    double userTime_Get(void)
    {
        int64_t TimeDiff = m_clock_time_begin.secsTo(QTime::currentTime());
    //    if(clock_time <0)  // we are overnight
    //        clock_time += 24*60*60*1000;
        return TimeDiff;
    }
    void userTime_Reset(void)
    {
        m_clock_time_begin = QTime::currentTime();
    }
    void scTime_Reset(void)
    {
        m_sc_time_begin = sc_core::sc_time_stamp();
    }
    sc_core::sc_time scTime_Get(void)
    {
        return sc_core::sc_time_stamp() - m_sc_time_begin;
    }
    void TimesReset()
    {
        scTime_Reset();
        userTime_Reset();
        systemTime_Reset();
    }
    // Return processor time from the benchmark, [us]
    double systemTime_Get()
    {
        return std::chrono::duration_cast<std::chrono::microseconds>(m_system_s).count();
    }
    void systemTime_Reset()
    {
        m_system_t =chrono::steady_clock::now();
        m_system_x = m_system_s = (std::chrono::duration< int64_t, nano>)0;
        BENCHMARK_TIME_RESET(&m_system_t,&m_system_x,&m_system_s); // Reset at the very beginning, say in the constructor
    }
    void NoOfSteps_Set(uint64_t N = 1){ m_NoOfSteps = N;}
    void TimeOfSteps_Set(sc_core::sc_time T = sc_core::sc_time(100,sc_core::SC_US)){ m_TimeOfAStep = T;}
    void SlowFactor_Set(uint64_t S){    m_SlowFactor = S;}
private:
    // Define time benchmarking variables and utility functions
    chrono::steady_clock::time_point m_system_t =chrono::steady_clock::now();
    std::chrono::duration< int64_t, nano> m_system_x,m_system_s = (std::chrono::duration< int64_t, nano>)0;
    uint64_t m_NoOfSteps = 1;
    uint64_t m_SlowFactor = 1000;
    sc_core::sc_time m_TimeOfAStep = sc_core::sc_time(100,sc_core::SC_US);
    sc_core::sc_time m_sc_time_begin;
    QTime m_clock_time_begin;   // The beginning of this simulation, [ms]
    /*
     * @brief Currently requested method
     */
    Method _method;
    /**
     * @brief Process is aborted when @em true
     */
    bool _abort;
    /**
     * @brief Current method is interrupted when @em true
     */
    bool _interrupt;
    /**
     * @brief Protects access to #_abort
     */
    QMutex mutex;
    /**
     * @brief Condition used to wait for a new request to be called in the #mainLoop()
     */
    QWaitCondition condition;
    /**
     * @brief Single event stepping mode
     *
     * Simulating is interrupted if #_abort or #_interrupt is set to true.
     */
    void doSimulationSteps();
    /**
     * @brief Simulated-time-limited stepping mode
     *
     * Simulating is interrupted if #_abort or #_interrupt is set to true.
     */
    void doSimulatedTime();
    /**
     * @brief 3rd method which could be called
     *
     * Counts 30 sec in this example.
     * Counting is interrupted if #_abort or #_interrupt is set to true.
     */
    void doMethod3();
signals:
    /**
     * @brief This signal is emitted when counted value is changed (every sec)
     */
    void valueChanged(const QString &value);
    /**
     * @brief This signal is emitted when  simulator returns from SystemC
      */
    void eventHappened(void);

    /**
     * @brief This signal is emitted when process is finished
     */
    void finished();

public slots:
    /**
     * @brief Waits for a method to be requested then executes it, then waits again
     *
     *
     */
    void mainLoop();
};

#endif // SCQTSIMULATOR_H
