#include "gitversion.h"

// The following header file is autogenerated by version.cmake, and will export
// a definition of the current git version for the build
#include "gen_versionnumber.h"


QString getGitVersion() { return QString(GIT_VERSION); }

